---
- name: To check the ansible lint example2
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and make sure Vim is installed
      ansible.builtin.yum:
        name: nginx
        update_cache: true
