name: Create pull request
on:
  push:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Make changes to pull request
      run: date +%s > report1.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          branch: develop
