name: ansible-lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Raise PR 1
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "vasagirisai-patch-1"
        base: main
        title: "demo for auto pr1"
        body:
            This is to show automatic PR creation
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: vasagirisai
