name: ansible-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Create Pull Request
      uses: vasagirisai/actions@main
      with:
        destination_branch: "main"
        source_branch: "vasagirisai-patch-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "feature, automated pr"
        pr_title: "Auto PR"
        pr_reviewer: "vasagirisai"
