name: ansible-lint

on:
  push:
    paths:
      - 'example.yml'

jobs:
  build:
    runs-on: redhat-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo yum install epel-release
        sudo yum install ansible
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint example.yml
