name: ansible-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Create PR
      if: success()
      run: |
          # Prompt the user for a PR title
          echo "Enter the PR title:"
          read title

          # Create the PR
          hub pull-request -m "$title"
