name: ansible-lint

on:
  push:
    branches:
      - vasagirisai-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Raise Pull Request
      uses: repo-sync/pull-request@v2
      with:
        branch: 'main'
        base: 'vasagirisai-patch-1'
        title: 'My Pull Request'
        body: 'This is the body of my pull request'
        label: 'enchancement'
        reviewers: 'vasagirisai'
