name: ansible-lint

on:
  push:
    branches: [vasagirisai-patch-2]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: create pull request
      run: gh pr create -B main -H vasagirisai-patch-2 --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
