name: ansible-lint

on:
  push:
    branches:
      - vasagirisai-patch-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: create pull request
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_PREFIX: vasagirisai-patch-2
        PULL_REQUEST_BRANCH: "main"
        PULL_REQUEST_REVIEWERS: vasagirisai
