name: Create pull request
on:
  push:
    branches:
      - vasagirisai-patch-2

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Pull Request
      id: pr
      uses: peter-evans/create-pull-request@v4
      with:
        delete-branch: false
        title: '[Github Action Bot] Update'
        commit-message: Update
        committer: GitHub Action Bot <action@github.com>
        author: GitHub Action Bot <action@github.com>
        branch: vasagirisai-patch-2
        branch-suffix: timestamp
        assignees: mietzen
        labels: |
            automated pr
            update
