name: ansible-lint

on: [push]

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Create Pull Request
      uses: vasagirisai/actions/action.yaml@v0
      with:
        destination_repository: main
        source_branch: vasagirisai-patch-2
        
