name: ansible-lint

on:
  push:
    branches:
      - vasagirisai-patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ansible
        sudo python -m pip install ansible-lint
    - name: Run ansible-lint
      run: |
        ansible-lint *.yml
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: create pull request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "vasagirisai-pr-1, automated pr"
        pr_title: "create pb_lint_check.yml"
    - name: Add Reviewers to Pull Request
      run: |
        curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
             -H "Accept: application/vnd.github+json" \
             -d "{\"reviewers\": [\"reviewer1\", \"reviewer2\"]}" \
             "https://api.github.com/repos/${GITHUB_CONTEXT.repository}/pulls/${GITHUB_CONTEXT.pull_request.number}/requested_reviewers"
