name: Create pull request
on:
  push:
    branches:
      - vasagirisai-patch-3

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "New feature"
        head: vasagirisai-patch-3
        base: main
